<a href="https://colab.research.google.com/github/Prakhar021-hub/Deep-Learning-Notebooks/blob/main/fundamentals%20of%20TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

In [4]:
print(tf.__version__) ## shows the version

2.18.0


In [5]:
## ways to create tensors
## tf.constant()

scalar = tf.constant(4)  ## tensor with 0 dimention
print(scalar)
print("the dimention of scalar is ", scalar.ndim)

tf.Tensor(4, shape=(), dtype=int32)
the dimention of scalar is  0


In [6]:
vector = tf.constant([1,3,5])  ## 1 dimention vector
print(vector)
print("the dimention of vector is ",vector.ndim )

tf.Tensor([1 3 5], shape=(3,), dtype=int32)
the dimention of vector is  1


In [7]:
matrix = tf.constant([[20,50,3], [45,67,23], [45,3,1]])
print(matrix)
print("the dimention is matrix is ", matrix.ndim)

tf.Tensor(
[[20 50  3]
 [45 67 23]
 [45  3  1]], shape=(3, 3), dtype=int32)
the dimention is matrix is  2


In [8]:
 ## by default the tensors uses int32 or float32 bits but we can change it to int64 or float64
 tf.constant([1,4,7], dtype = 'float64')


<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 4., 7.])>

In [9]:
## creating a tensor with more than 2 dimention ("using variable method")

dim = tf.Variable([[[1,2,3],[1,4,6],
             [2,4,5], [4,6,8]],
             [[3,5,5], [6,7,8],
              [90, 5,7], [20,40,50]],
             [[2,4,6], [41,45,32],
              [3,5,6], [5,6,6]]])
print(dim)
print(dim.shape.rank)

<tf.Variable 'Variable:0' shape=(3, 4, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 1,  4,  6],
        [ 2,  4,  5],
        [ 4,  6,  8]],

       [[ 3,  5,  5],
        [ 6,  7,  8],
        [90,  5,  7],
        [20, 40, 50]],

       [[ 2,  4,  6],
        [41, 45, 32],
        [ 3,  5,  6],
        [ 5,  6,  6]]], dtype=int32)>
3


In [10]:
dim[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(3, 4, 3) dtype=int32, numpy=
array([[[ 7,  7,  7],
        [ 7,  7,  7],
        [ 7,  7,  7],
        [ 7,  7,  7]],

       [[ 3,  5,  5],
        [ 6,  7,  8],
        [90,  5,  7],
        [20, 40, 50]],

       [[ 2,  4,  6],
        [41, 45, 32],
        [ 3,  5,  6],
        [ 5,  6,  6]]], dtype=int32)>

In [11]:
# Change first row of first slice
dim.scatter_nd_update(indices=[[0,2,2]], updates=[40])


<tf.Variable 'UnreadVariable' shape=(3, 4, 3) dtype=int32, numpy=
array([[[ 7,  7,  7],
        [ 7,  7,  7],
        [ 7,  7, 40],
        [ 7,  7,  7]],

       [[ 3,  5,  5],
        [ 6,  7,  8],
        [90,  5,  7],
        [20, 40, 50]],

       [[ 2,  4,  6],
        [41, 45, 32],
        [ 3,  5,  6],
        [ 5,  6,  6]]], dtype=int32)>

In [12]:
## generating random data for tensors

random1 = tf.random.Generator.from_seed(3)
random1 = random1.normal(shape= (2,3))
print(random1)
random2 = tf.random.Generator.from_non_deterministic_state()## another way to if u dont want to use seed to generate the data
random2 = random2.normal(shape = (3,4))
print(random2)
random3 = tf.random.normal(shape = (3,4)) ## other methods to to create the noraml dist. data without using generator
print(random3)
random4 = tf.random.uniform(shape = (3,2)) ## """"""""""
print(random4)


tf.Tensor(
[[-0.43640924 -1.9633987  -0.06452483]
 [-1.056841    1.0019137   0.6735137 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 0.9099362   0.4545562   0.79837286  0.43907148]
 [-0.27823457 -0.4518493  -0.01803906  1.3971953 ]
 [ 0.5054653   1.6541299   0.20141093  2.9506106 ]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[ 1.1236992   1.7566245   0.46661422  0.36754668]
 [ 0.09365119 -0.50233084  0.24886407 -1.794646  ]
 [-0.85061884 -0.13418937 -0.12262925 -1.0889491 ]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[0.14278293 0.9344915 ]
 [0.11386549 0.68738663]
 [0.01327074 0.69987845]], shape=(3, 2), dtype=float32)


In [13]:
### shuffle the data

not_shuffle = tf.constant([[1,2,3],
                          [4,5,6]])
tf.random.shuffle(not_shuffle)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [1, 2, 3]], dtype=int32)>

In [14]:
### others ways to create the tensors

print(tf.ones(shape =(3,3)))
print(tf.zeros(shape =(3,3)))


tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [15]:
## creating tensors using numpy

import numpy as np
numpy_a = np.arange(1,28)

ten = tf.constant(numpy_a, shape = [3,3,3])
print(ten)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]], shape=(3, 3, 3), dtype=int64)


In [16]:
## creating a rank 4 tensor
np_4 = np.arange(1,121)
tensor_4 = tf.constant(np_4, shape = [2,3,4,5])
print(tensor_4)

tf.Tensor(
[[[[  1   2   3   4   5]
   [  6   7   8   9  10]
   [ 11  12  13  14  15]
   [ 16  17  18  19  20]]

  [[ 21  22  23  24  25]
   [ 26  27  28  29  30]
   [ 31  32  33  34  35]
   [ 36  37  38  39  40]]

  [[ 41  42  43  44  45]
   [ 46  47  48  49  50]
   [ 51  52  53  54  55]
   [ 56  57  58  59  60]]]


 [[[ 61  62  63  64  65]
   [ 66  67  68  69  70]
   [ 71  72  73  74  75]
   [ 76  77  78  79  80]]

  [[ 81  82  83  84  85]
   [ 86  87  88  89  90]
   [ 91  92  93  94  95]
   [ 96  97  98  99 100]]

  [[101 102 103 104 105]
   [106 107 108 109 110]
   [111 112 113 114 115]
   [116 117 118 119 120]]]], shape=(2, 3, 4, 5), dtype=int64)


In [17]:
## we can perform indexing on this tensor

tensor_4[:2,:2,:2,:3]

<tf.Tensor: shape=(2, 2, 2, 3), dtype=int64, numpy=
array([[[[ 1,  2,  3],
         [ 6,  7,  8]],

        [[21, 22, 23],
         [26, 27, 28]]],


       [[[61, 62, 63],
         [66, 67, 68]],

        [[81, 82, 83],
         [86, 87, 88]]]])>

In [18]:
## extract 43 ,44, 48,49

tensor_4[0,2,0:2, 2:4 ]

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[43, 44],
       [48, 49]])>

In [19]:
tensor_4[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=int64, numpy=array([[[[1, 2, 3, 4, 5]]]])>

In [20]:
### Matrix Multification

In [23]:
X = tf.constant([[1,2,3],
                 [2,3,4]])

Y = tf.constant([[1,2],
                [2,4],
                [4,5]])

Z = tf.constant([[4,6,8],
                [5,2,6]])

In [22]:
X @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[17, 25],
       [24, 36]], dtype=int32)>

In [25]:
X @ Z ## not possible becoz of matrix properties

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [2,3], In[1]: [2,3] [Op:MatMul] name: 

In [26]:
## we need to reshape or transpose either of the one matrix

## reshape

X @ tf.reshape(Z, shape= (3,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 34],
       [40, 51]], dtype=int32)>

In [27]:
## transpose

Z @ tf.transpose(X)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[40, 58],
       [27, 40]], dtype=int32)>

In [28]:
## we can also use the function matmul() for multiplication

tf.matmul(X , tf.transpose(Z))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[40, 27],
       [58, 40]], dtype=int32)>

In [29]:
## or in a way

tf.matmul(X,Z, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[14, 10, 20],
       [23, 18, 34],
       [32, 26, 48]], dtype=int32)>

In [36]:
## rev and transpose gives different result
rev = tf.constant([[2,3,4],[3, 4, 6]])
rev

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [3, 4, 6]], dtype=int32)>

In [33]:
tf.reshape(rev, shape = (3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 3],
       [4, 6]], dtype=int32)>

In [35]:
tf.transpose(rev)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [3, 4],
       [4, 6]], dtype=int32)>

In [37]:
## performing aggrigate functions

tens = tf.constant(np.random.randint(low = 0, high = 100, size=50))
tens

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([38, 69, 42,  2, 58, 94, 45, 92, 29, 79, 57, 70,  1, 39, 94, 97, 13,
       79, 41,  6, 92, 98, 59, 23, 58, 47, 39, 53, 77, 20, 76, 88, 73, 46,
       83, 20, 24, 43, 45, 48, 38, 29,  5, 26,  7, 49, 11, 38, 13, 16])>

In [39]:
print("maximum",tf.reduce_max(tens))
print("minimum",tf.reduce_min(tens))
print("mean" ,tf.reduce_mean(tens))
print("sum", tf.reduce_sum(tens))

maximum tf.Tensor(98, shape=(), dtype=int64)
minimum tf.Tensor(1, shape=(), dtype=int64)
mean tf.Tensor(47, shape=(), dtype=int64)
sum tf.Tensor(2389, shape=(), dtype=int64)


In [41]:
## getting the index oof thr maximum and minimum values

print("the index of the smallest element is : ", tf.argmin(tens))
print("the index of the greatest element is : ", tf.argmax(tens))


the index of the smallest element is :  tf.Tensor(12, shape=(), dtype=int64)
the index of the greatest element is :  tf.Tensor(21, shape=(), dtype=int64)
